name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: bazel
        run: buildifier -mode check -lint warn -r .
      - name: csharp
        run: dotnet format KRPC2.sln --verify-no-changes --exclude bazel-bin

  build-krpc2-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: ksp-lib
        uses: krpc/krpc-core/.github/actions/ksp-lib@main
        with:
          game: ksp2
          version: 0.1.1
      - name: build
        run: bazel build //:krpc2
      - name: upload-krpc-artifact
        uses: krpc/krpc-core/.github/actions/upload-artifact@main
        with:
          name: krpc
          path: bazel-bin/krpc2-*.zip

  build-krpc2-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: ksp-lib
        uses: krpc/krpc-core/.github/actions/ksp-lib@main
        with:
          game: ksp2
          version: 0.1.1
      - name: build
        run: bazel --bazelrc=.github/workflows/bazelrc build //:krpc2

  build-krpc2-nix-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix flake check
      # TODO: We can add the build to a cache for others (see cachix.org)
      # It's free for FOSS.
      - run: nix build .#krpc2

  build-krpc2-sln-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: ksp-lib
        uses: krpc/krpc-core/.github/actions/ksp-lib@main
        with:
          game: ksp2
          version: 0.1.1
      - name: deps
        run: bazel build //:csproj
      - name: build
        run: dotnet build KRPC2.sln

  build-krpc2-sln-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: ksp-lib
        uses: krpc/krpc-core/.github/actions/ksp-lib@main
        with:
          game: ksp2
          version: 0.1.1
      - name: deps
        run: bazel --bazelrc=.github/workflows/bazelrc build //:csproj
      - name: build
        run: dotnet build KRPC2.sln
